version: '3.5'
services:
  test-automation-deployment:
    container_name: test-deployment 
    build: .
    restart: unless-stopped
networks:
    default:
        name: idea
        external: true

